const INDUSTRIAS = [
  { codigo: 39, nome: "CIFARMA", nomePadrao: "CIFARMA FARMA", aliases: ["CIFARMA PROPAGANDA MEDICA"] },
  { codigo: 180, nome: "ECOFITUS", nomePadrao: "ECOFITUS" },
  { codigo: 56, nome: "EMS", nomePadrao: "EMS" },
  { codigo: 875, nome: "EMS GENERICO", nomePadrao: "EMS GENERICO" },
  { codigo: 60, nome: "EUROFARMA", nomePadrao: "EUROFARMA" },
  { codigo: 9, nome: "GEOLAB", nomePadrao: "GEOLAB" },
  { codigo: 68, nome: "KLEY HERTZ", nomePadrao: "KLEY HERTZ" },
  { codigo: 4, nome: "LEGRAND GENERICOS", nomePadrao: "LEGRAND GENERICOS" },
  { codigo: 2, nome: "LEGRAND TARJADOS", nomePadrao: "LEGRAND TARJADOS" },
  { codigo: 193, nome: "MAXINUTRI", nomePadrao: "MAXINUTRI" },
  { codigo: 8, nome: "MULTILAB", nomePadrao: "MULTILAB" },
  { codigo: 85, nome: "NATULAB", nomePadrao: "NATULAB" },
  { codigo: 5, nome: "NEO QUIMICA GENERICO", nomePadrao: "NEO QUIMICA GENERICO" },
  { codigo: 1, nome: "NEO QUIMICA SMART", nomePadrao: "NEO QUIMICA SMART" },
  { codigo: 3, nome: "TEUTO", nomePadrao: "TEUTO" },
  { codigo: 118, nome: "VITAMEDIC", nomePadrao: "VITAMEDIC" },

  { codigo: 778, nome: "3B", nomePadrao: "3B" },
  { codigo: 750, nome: "ABOVE", nomePadrao: "ABOVE" },
  { codigo: 10, nome: "ACCUMED", nomePadrao: "ACCUMED" },
  { codigo: 11, nome: "ADDIT", nomePadrao: "ADDIT" },
  { codigo: 12, nome: "ADV LAB TAYUYNA", nomePadrao: "ADV LAB TAYUYNA", aliases: ["ADV"] },
  { codigo: 231, nome: "AIRELA", nomePadrao: "AIRELA" },
  { codigo: 882, nome: "ALPHAFITUS CREATINA", nomePadrao: "ALPHAFITUS CREATINA" },
  { codigo: 909, nome: "AMAKHA PARIS", nomePadrao: "AMAKHA PARIS" },
  { codigo: 15, nome: "ANALITIC", nomePadrao: "ANALITIC" },
  { codigo: 18, nome: "ARTE NATIVA VELTOFARMA", nomePadrao: "ARTE NATIVA VELTOFARMA" },
  { codigo: 873, nome: "AVIZOR", nomePadrao: "AVIZOR" },
  { codigo: 863, nome: "AVVIO", nomePadrao: "AVVIO" },
  { codigo: 868, nome: "BEIRA ALTA", nomePadrao: "BEIRA ALTA" },
  { codigo: 169, nome: "BELFAR", nomePadrao: "BELFAR" },
  { codigo: 859, nome: "BELLAPHYTUS", nomePadrao: "BELLAPHYTUS" },
  { codigo: 24, nome: "BIONATUS", nomePadrao: "BIONATUS" },
  { codigo: 28, nome: "BRASTERAPICA", nomePadrao: "BRASTERAPICA" },
  { codigo: 779, nome: "BREYER", nomePadrao: "BREYER" },
  { codigo: 31, nome: "BUTTERFLY", nomePadrao: "BUTTERFLY" },
  { codigo: 32, nome: "C M HOSPITALAR", nomePadrao: "C M HOSPITALAR" },
  { codigo: 742, nome: "CARTA FABRIL", nomePadrao: "CARTA FABRIL" },
  { codigo: 34, nome: "CATARINENSE", nomePadrao: "CATARINENSE" },
  { codigo: 35, nome: "CATARINENSE MATACURA", nomePadrao: "CATARINENSE MATACURA" },
  { codigo: 36, nome: "CAZI", nomePadrao: "CAZI" },
  { codigo: 843, nome: "CCM", nomePadrao: "CCM" },
  { codigo: 49, nome: "CELLERA DELTA", nomePadrao: "CELLERA DELTA" },
  { codigo: 179, nome: "CIFARMA PROPAGANDA MEDICA", nomePadrao: "CIFARMA", aliases: ["CIFARMA FARMA"] },
  { codigo: 40, nome: "CIMED", nomePadrao: "CIMED" },
  { codigo: 41, nome: "CIRURGICA FERNANDES", nomePadrao: "CIRURGICA FERNANDES" },
  { codigo: 724, nome: "COMERCIO E DISTRIBUIDORA DELTA", nomePadrao: "COMERCIO E DISTRIBUIDORA DELTA" },
  { codigo: 44, nome: "CREMER", nomePadrao: "CREMER" },
  { codigo: 46, nome: "DKT", nomePadrao: "DKT" },
  { codigo: 893, nome: "DACOLONIA", nomePadrao: "DACOLONIA" },
  { codigo: 865, nome: "DENTAL CLEAN", nomePadrao: "DENTAL CLEAN" },
  { codigo: 53, nome: "DIVON", nomePadrao: "DIVON" },
  { codigo: 54, nome: "DORJA", nomePadrao: "DORJA" },
  { codigo: 889, nome: "DR PEANUT", nomePadrao: "DR PEANUT" },
  { codigo: 894, nome: "DRICA", nomePadrao: "DRICA" }
];

module.exports = { INDUSTRIAS };